use std::path::{Path, PathBuf};
pub const SHIM_DIR_NAME: &str = "pnpm-home";

pub fn bundled_entry(resource_dir: &Path) -> Option<PathBuf> {
    ["pnpm/bin/pnpm.mjs", "pnpm/bin/pnpm.cjs"]
        .iter()
        .map(|rel| resource_dir.join(rel))
        .find(|p| p.is_file())
}

pub fn shim_dir(app_data: &Path) -> PathBuf {
    app_data.join(SHIM_DIR_NAME)
}

#[cfg_attr(windows, allow(dead_code))]
pub fn posix_shim(node: &Path, entry: &Path) -> String {
    format!(
        "#!/bin/sh\n\
         # Generated by DSH Desktop - runs the bundled pnpm with the bundled Node.\n\
         # Rewritten on every startup; do not edit.\n\
         exec {} {} \"$@\"\n",
        sh_quote(node),
        sh_quote(entry),
    )
}

#[cfg_attr(unix, allow(dead_code))]
pub fn cmd_shim(node: &Path, entry: &Path) -> String {
    format!(
        "@echo off\r\n\
         rem Generated by DSH Desktop - runs the bundled pnpm with the bundled Node.\r\n\
         rem Rewritten on every startup; do not edit.\r\n\
         \"{}\" \"{}\" %*\r\n\
         exit /b %ERRORLEVEL%\r\n",
        node.display(),
        entry.display(),
    )
}

#[cfg_attr(windows, allow(dead_code))]
fn sh_quote(p: &Path) -> String {
    format!("'{}'", p.to_string_lossy().replace('\'', r"'\''"))
}

pub fn with_dir_first(current: &str, dir: &Path, sep: char) -> String {
    let dir = dir.to_string_lossy().to_string();
    let mut parts: Vec<String> = current
        .split(sep)
        .filter(|p| !p.is_empty() && *p != dir)
        .map(|p| p.to_string())
        .collect();
    parts.insert(0, dir);
    parts.join(&sep.to_string())
}

#[cfg(windows)]
fn write_script(path: &Path, text: &str) -> std::io::Result<()> {
    use winapi::um::stringapiset::WideCharToMultiByte;
    use winapi::um::winnls::{GetOEMCP, WC_NO_BEST_FIT_CHARS};

    let wide: Vec<u16> = text.encode_utf16().collect();
    let cp = unsafe { GetOEMCP() };
    let mut lossy: i32 = 0;
    let mut convert = |buf: *mut u8, len: i32| unsafe {
        WideCharToMultiByte(
            cp,
            WC_NO_BEST_FIT_CHARS,
            wide.as_ptr(),
            wide.len() as i32,
            buf as *mut i8,
            len,
            std::ptr::null(),
            &mut lossy,
        )
    };

    let len = convert(std::ptr::null_mut(), 0);
    if len <= 0 {
        return Err(std::io::Error::last_os_error());
    }
    let mut buf = vec![0u8; len as usize];
    let n = convert(buf.as_mut_ptr(), len);
    if n <= 0 {
        return Err(std::io::Error::last_os_error());
    }
    buf.truncate(n as usize);
    if lossy != 0 {
        log::warn!("pnpm: 路径含代码页 {cp} 无法表示的字符，pnpm 可能无法启动");
    }
    std::fs::write(path, &buf)
}

#[cfg(unix)]
fn write_script(path: &Path, text: &str) -> std::io::Result<()> {
    std::fs::write(path, text)
}

pub fn write_shim(dir: &Path, node: &Path, entry: &Path) -> Result<PathBuf, String> {
    let node = crate::node::normalize_for_node(node);
    let entry = crate::node::normalize_for_node(entry);
    std::fs::create_dir_all(dir).map_err(|e| format!("创建 pnpm 目录失败: {e}"))?;
    #[cfg(windows)]
    let file = {
        let path = dir.join("pnpm.cmd");
        write_script(&path, &cmd_shim(&node, &entry)).map_err(|e| format!("写入 pnpm.cmd 失败: {e}"))?;
        path
    };
    #[cfg(unix)]
    let file = {
        use std::os::unix::fs::PermissionsExt;
        let path = dir.join("pnpm");
        write_script(&path, &posix_shim(&node, &entry)).map_err(|e| format!("写入 pnpm 失败: {e}"))?;
        let mut perms = std::fs::metadata(&path)
            .map_err(|e| format!("读取 pnpm 权限失败: {e}"))?
            .permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&path, perms).map_err(|e| format!("设置 pnpm 权限失败: {e}"))?;
        path
    };
    Ok(file)
}

pub fn activate(resource_dir: &Path, app_data: &Path) -> Option<PathBuf> {
    let entry = bundled_entry(resource_dir)?;
    let node = match crate::node::resolve_node(resource_dir) {
        Ok(p) => p,
        Err(e) => {
            log::warn!("pnpm: bundled node unavailable, market keeps system pnpm: {e}");
            return None;
        }
    };
    let dir = shim_dir(app_data);
    if let Err(e) = write_shim(&dir, &node, &entry) {
        log::warn!("pnpm: shim not written, market keeps system pnpm: {e}");
        return None;
    }

    let sep = if cfg!(windows) { ';' } else { ':' };
    let current = std::env::var("PATH").unwrap_or_default();
    std::env::set_var("PATH", with_dir_first(&current, &dir, sep));
    log::info!(
        "pnpm: bundled pnpm active ({}) for the plugin market",
        dir.display()
    );
    Some(dir)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("dsh-pnpm-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn bundled_entry_finds_pnpm_package() {
        let root = temp("entry");
        assert_eq!(bundled_entry(&root), None, "no bundle packaged");

        let bin = root.join("pnpm").join("bin");
        std::fs::create_dir_all(&bin).unwrap();
        std::fs::write(bin.join("pnpm.cjs"), "// old layout").unwrap();
        assert_eq!(bundled_entry(&root), Some(bin.join("pnpm.cjs")));

        std::fs::write(bin.join("pnpm.mjs"), "// current layout").unwrap();
        assert_eq!(
            bundled_entry(&root),
            Some(bin.join("pnpm.mjs")),
            "pnpm.mjs wins when both exist"
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn with_dir_first_prepends_and_dedupes() {
        let dir = PathBuf::from("/opt/pnpm-home");
        assert_eq!(
            with_dir_first("/usr/bin:/bin", &dir, ':'),
            "/opt/pnpm-home:/usr/bin:/bin"
        );
        // Already present further down: moved to the front, not duplicated.
        assert_eq!(
            with_dir_first("/usr/bin:/opt/pnpm-home:/bin", &dir, ':'),
            "/opt/pnpm-home:/usr/bin:/bin"
        );
        // Empty and trailing entries are dropped.
        assert_eq!(with_dir_first(":/usr/bin:", &dir, ':'), "/opt/pnpm-home:/usr/bin");
        assert_eq!(with_dir_first("", &dir, ':'), "/opt/pnpm-home");
        // Windows separator.
        assert_eq!(
            with_dir_first(r"C:\Windows", &PathBuf::from(r"C:\pnpm"), ';'),
            r"C:\pnpm;C:\Windows"
        );
    }

    #[test]
    fn posix_shim_execs_bundled_pair_and_quotes_spaces() {
        let shim = posix_shim(
            Path::new("/Applications/DSH Work 台/node"),
            Path::new("/Applications/DSH Work 台/pnpm/bin/pnpm.mjs"),
        );
        assert!(shim.starts_with("#!/bin/sh\n"));
        assert!(shim.contains(
            "exec '/Applications/DSH Work 台/node' '/Applications/DSH Work 台/pnpm/bin/pnpm.mjs' \"$@\""
        ));
        // A quote in the path must not break out of the quoting.
        let quoted = posix_shim(Path::new("/tmp/it's/node"), Path::new("/tmp/pnpm.mjs"));
        assert!(quoted.contains(r"'/tmp/it'\''s/node'"));
    }

    #[test]
    fn cmd_shim_passes_arguments_and_exit_code() {
        let shim = cmd_shim(
            Path::new(r"C:\Program Files\node\node.exe"),
            Path::new(r"C:\app\pnpm\bin\pnpm.mjs"),
        );
        assert!(shim.contains(r#""C:\Program Files\node\node.exe" "C:\app\pnpm\bin\pnpm.mjs" %*"#));
        assert!(shim.contains("exit /b %ERRORLEVEL%"));
    }

    #[cfg(unix)]
    #[test]
    fn write_shim_creates_executable_pnpm() {
        use std::os::unix::fs::PermissionsExt;
        let dir = temp("write");
        let path = write_shim(
            &dir.join("pnpm-home"),
            Path::new("/usr/local/bin/node"),
            Path::new("/opt/pnpm/bin/pnpm.mjs"),
        )
        .unwrap();
        assert_eq!(path.file_name().unwrap(), "pnpm");
        let mode = std::fs::metadata(&path).unwrap().permissions().mode();
        assert!(mode & 0o111 != 0, "shim must be executable: {mode:o}");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[cfg(windows)]
    #[test]
    fn write_shim_creates_pnpm_cmd() {
        let dir = temp("write");
        let path = write_shim(
            &dir.join("pnpm-home"),
            Path::new(r"C:\node\node.exe"),
            Path::new(r"C:\app\pnpm\bin\pnpm.mjs"),
        )
        .unwrap();
        assert_eq!(path.file_name().unwrap(), "pnpm.cmd");
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(text.contains("%*"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[cfg(windows)]
    #[test]
    fn write_shim_strips_verbatim_prefix() {
        let dir = temp("verbatim");
        let path = write_shim(
            &dir.join("pnpm-home"),
            Path::new(r"\\?\C:\node\node.exe"),
            Path::new(r"\\?\C:\app\pnpm\bin\pnpm.mjs"),
        )
        .unwrap();
        let text = String::from_utf8_lossy(&std::fs::read(&path).unwrap()).to_string();
        assert!(
            !text.contains(r"\\?\"),
            "cmd.exe reads a verbatim path as UNC: {text}"
        );
        assert!(text.contains(r#""C:\node\node.exe" "C:\app\pnpm\bin\pnpm.mjs""#));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[cfg(windows)]
    #[test]
    fn shim_runs_when_the_install_dir_is_not_ascii() {
        let node = Path::new(env!("CARGO_MANIFEST_DIR")).join("../resources/node/win-x64/node.exe");
        if !node.is_file() {
            return;
        }
        let dir = temp("café");
        let script = dir.join("probe.mjs");
        std::fs::write(&script, "console.log('shim-ok')\n").unwrap();

        let shim = write_shim(
            &dir.join("pnpm-home"),
            &node,
            &PathBuf::from(format!(r"\\?\{}", script.display())),
        )
        .unwrap();

        let out = std::process::Command::new("cmd")
            .arg("/c")
            .arg(&shim)
            .output()
            .unwrap();
        assert!(
            String::from_utf8_lossy(&out.stdout).contains("shim-ok"),
            "stdout={:?} stderr={:?}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr),
        );
        let _ = std::fs::remove_dir_all(&dir);
    }
}
